### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by liwenjielongren** [feiyuhuahuo/Anomaly_Prediction#1]
I run train.py a night. But nothing was showed on the terminal.how long do you train?
![image](https://user-images.githubusercontent.com/52265815/70773671-0ea0eb80-1db3-11ea-8e05-bab883b3945e.png)

**Comment by feiyuhuahuo** [comment]
This is because the Dataloader didn't get the data. Check the path of your avenue data, it should match with this: 
![image](https://user-images.githubusercontent.com/32631344/70777653-4c097700-1dbb-11ea-903a-1983582531b3.png)

**Comment by liwenjielongren** [comment]
indeed,but I used two  GPU and show didn't enough memory
![image](https://user-images.githubusercontent.com/52265815/70792025-56376f80-1dd3-11ea-8a54-c2e5f0bd0f43.png)

**Comment by liwenjielongren** [comment]
![image](https://user-images.githubusercontent.com/52265815/70792150-8da61c00-1dd3-11ea-8c6d-f8586e464142.png)

**Comment by feiyuhuahuo** [comment]
what＇s your pytorch version and your batch size？

**Comment by liwenjielongren** [comment]
torch1.1.0 and batch size==8,

**Comment by feiyuhuahuo** [comment]
That's strange. It works fine with me. Try again. Or try `export CUDA_VISIBLE_DEVICES=0` before you run train.py.

**Comment by liwenjielongren** [comment]
ok, thinks.

**Comment by GreatEngineer** [comment]
I write os.environ['CUDA_VISIBLE_DEVICES']='3' in the train.py file to make it run in the third gpu, but it still run in the 0 gpu and run out of memory, how can I solve this? I want to set the gpu id

**Comment by feiyuhuahuo** [comment]
@GreatEngineer That seems to be a bug for pytorch. I don't know why. You need to use `export CUDA_VISIBLE_DEVICES=3` in the terminal before you run train.py.

**Comment by liwenjielongren** [comment]
torch.cuda.set_device(id)

**Comment by GreatEngineer** [comment]
are your results are the best value?  When I  run the code to train, the value every time can be different, and hard to up to 95.6

**Comment by feiyuhuahuo** [comment]
95.6 is the best result. But at least result> 95.0 can be got.  Set a smaller val_interval and choose a best result. Or try to use batch_size=4 (keep the lr unchanged), large batch_size does not get better results when I was training.

**Comment by GreatEngineer** [comment]
ok, thanks very much
