### ISSUE TITLE
Other datasets

### ISSUE THREAD

**Issue by herundong** [feiyuhuahuo/Anomaly_Prediction#10]
hello,have you run experiments on other datasets (like ped1 and shanghaitech)? Is there a weights file for these two datasets?

**Comment by feiyuhuahuo** [comment]
I got a wrong image after unzipping ped1 and shanghaitech is too large. So did not run on them both.

**Comment by herundong** [comment]
Thank you very much, and I would like to ask about the setting of the parameters in ped2 (lr and the proportion of each loss).

**Comment by abhishekaich27** [comment]
@feiyuhuahuo What do you mean by wrong image with ped1?
