### ISSUE TITLE
When I run python train.py --dataset=avenue,The following problems arise

### ISSUE THREAD

**Issue by fatancy2580** [feiyuhuahuo/Anomaly_Prediction#13]
![image](https://user-images.githubusercontent.com/52057084/99941009-40cf1180-2da8-11eb-9d4f-7195049951a0.png)

**Comment by feiyuhuahuo** [comment]
What's your cupy version? Try to update cupy.

**Comment by fatancy2580** [comment]
My CUDA version ==10.1,so the cupy-cuda101 was installed.updating cupy is necessary??

**Comment by fatancy2580** [comment]
> What's your cupy version? Try to update cupy.

My CUDA version ==10.1,so the cupy-cuda101 was installed.updating cupy is necessary??

**Comment by fatancy2580** [comment]
> What's your cupy version? Try to update cupy.

my ubuntu== 19.10 and CUDA version ==10.1,so the cupy-cuda101 was installed.updating cupy is necessary??

**Comment by fatancy2580** [comment]
Hi! Thanks for your work！And l have to questions
My ubuntu== 19.10 and CUDA version ==10.1,so the cupy-cuda101 was installed.updating cupy is necessary??

**Comment by fatancy2580** [comment]
> What's your cupy version? Try to update cupy.

Hi! Thanks for your work！And l have to questions
My ubuntu== 19.10 and CUDA version ==10.1,so the cupy-cuda101 was installed.updating cupy is necessary??
Looking foward to your reply.Thank you again

**Comment by fatancy2580** [comment]
> What's your cupy version? Try to update cupy.

Hi! Thanks for your work！And l have a question.
My ubuntu== 19.10 and CUDA version ==10.1,so the cupy-cuda101 was installed.updating cupy is necessary??
Looking foward to your reply.Thank you again

**Comment by feiyuhuahuo** [comment]
In my package list, the package name for cupy is only 'cupy', not 'cupy-cuda101'. 
You may try this: `pip install cupy==6.0.0`

**Comment by fatancy2580** [comment]
> In my package list, the package name for cupy is only 'cupy', not 'cupy-cuda101'.
> You may try this: `pip install cupy==6.0.0`

Thank you for your reply. What is your Linux version??

**Comment by fatancy2580** [comment]
> > In my package list, the package name for cupy is only 'cupy', not 'cupy-cuda101'.
> > You may try this: `pip install cupy==6.0.0`
> 
> Thank you for your reply. What is your Linux version??

Thank you for your code I have solved the problem

**Comment by feiyuhuahuo** [comment]
Ubuntu18.04

**Comment by fatancy2580** [comment]
> Ubuntu18.04

Thank you .respect

**Comment by sthoduka** [comment]
The other option is to change `cupy.util.memoize` to `cupy.memoize` since `cupy.util` was removed since version 8
