### ISSUE TITLE
About AUC

### ISSUE THREAD

**Issue by rrxi** [feiyuhuahuo/Anomaly_Prediction#15]
I want to know how to get AUC value? Thanks.

**Comment by feiyuhuahuo** [comment]
AUC will be computed and printed after you finished evaluation.

**Comment by Yii-maker** [comment]
Hello, I have the following questions about AUC: 
1. In the original text, the AUC on the CUHK Avenue dataset seems to be 85.1%, but what you said in the readme file is 84.9% .
2. In your work, the best time is when you train for the 1800th time, but you used the 15000th AUC. Why?
 I don’t know if my thinking is wrong?

**Comment by feiyuhuahuo** [comment]
1. The paper shows it's 84.9%.
![图片](https://user-images.githubusercontent.com/32631344/101850372-98d18a80-3b94-11eb-9e73-30d821ca8c4c.png)

2. When I was training, the best AUC appears at 15000th. But this project converges quickly. It's normal if you get your best AUC at a different iteration.

**Comment by rrxi** [comment]
> AUC will be computed and printed after you finished evaluation.

Thanks for you.
