### ISSUE TITLE
About the version of python pytorch cuda 

### ISSUE THREAD

**Issue by sgq123** [feiyuhuahuo/Anomaly_Prediction#17]
hi, when i trained this net, it showed"segmentation fault(core dumped)"
i want to know the specific version of your python,pytorch,cuda,thanks!

**Comment by feiyuhuahuo** [comment]
I sometimes encountered the same error. You can try to start a new terminal or restart the computer.
Besides, this project should run well with Python>=3.6, PyTorch>=1.1, CUDA>=10.1.

**Comment by sgq123** [comment]
> I sometimes encountered the same error. You can try to start a new terminal or restart the computer.
> Besides, this project should run well with Python>=3.6, PyTorch>=1.1, CUDA>=10.1.

thanks,let me try

**Comment by sgq123** [comment]
> I sometimes encountered the same error. You can try to start a new terminal or restart the computer.
> Besides, this project should run well with Python>=3.6, PyTorch>=1.1, CUDA>=10.1.

Hi,I found that every time the program ran to the following command, it crashed,it will said"segmentation fault(core dumped)"
`writer.add_image('image/G_frame', save_G_frame, global_step=step)`
or
`writer.add_scalar('results/auc', auc, global_step=step)`
Further, I found that the reason for the error in executing the `writer.add_scalar('results/auc', auc, global_step=step)` command was due to an error in the **auc** calculation(I haven't checked why the `writer.add_image('image/G_frame', save_G_frame, global_step=step)` command went wrong)

so i think maybe there is something wrong in evaluate.py when computing auc
Therefore, I want to ask whether you can successfully execute the above command now. If so, it should be my environment configuration error. Please tell me the **exact environment version**(python,pytorch,cuda) where you can successfully execute the code at present.
Thank you so much!!

**Comment by feiyuhuahuo** [comment]
My current environment is python3.7, PyTorch1.7, CUDA10.2. But this project also runs well on my old environment:Python3.7, PyTorch1.1, CUDA10.1. You can also try to update tensorboard and tensorboardx. Or you can directly comment code about tensorboard. They are just for recording.

**Comment by sgq123** [comment]
> My current environment is python3.7, PyTorch1.7, CUDA10.2. But this project also runs well on my old environment:Python3.7, PyTorch1.1, CUDA10.1. You can also try to update tensorboard and tensorboardx. Or you can directly comment code about tensorboard. They are just for recording.

thanks!

**Comment by sgq123** [comment]
> My current environment is python3.7, PyTorch1.7, CUDA10.2. But this project also runs well on my old environment:Python3.7, PyTorch1.1, CUDA10.1. You can also try to update tensorboard and tensorboardx. Or you can directly comment code about tensorboard. They are just for recording.

I googled [The different order of import SummaryWriter may cause Segmentation fault](https://github.com/pytorch/pytorch/issues/30651)
I just changed the order...
i don't know why ,but it really works.....

**Comment by feiyuhuahuo** [comment]
I really have no idea about this.
