### ISSUE TITLE
segmentation fault (core dumped) error?

### ISSUE THREAD

**Issue by Jaborie203** [feiyuhuahuo/Anomaly_Prediction#18]
The work is very niubility, and I appreciate it. But when i exec the "train.py" for about 100 epoch, the terminal display "segmentation fault (core dumped)". I try to solve this problem, but i failed. Anyone can help me? thank you very very very very muchhhhh!

**Comment by feiyuhuahuo** [comment]
Open a new terminal to start your training or just restart your computer just in case.

**Comment by Jaborie203** [comment]
Best project! Thank you @feiyuhuahuo  for your reply. I put the code "from tensorboardX import SummaryWriter" at the top and the problem was solved!
