### ISSUE TITLE
About the lite-flownet

### ISSUE THREAD

**Issue by ZhaoBin9102** [feiyuhuahuo/Anomaly_Prediction#19]
Hi！Do you use the pre-training weights of the lite-flownet author ? Also, which version of lite-flownet are you using？thank you very
 much！

**Comment by feiyuhuahuo** [comment]
Pre-trained weights of lite-flownet is used. The code is also from github but I forgot which project I use.

**Comment by ZhaoBin9102** [comment]
Do you use the same lite-flownet weight as this (https://github.com/fjchange/pytorch_ano_pre) project?

**Comment by feiyuhuahuo** [comment]
I borrowed some code from that project. I don't know whether I used the same weight. There are several weights from a pytorch liteflownet project. I tested them all, and the results are almost same.

**Comment by ZhaoBin9102** [comment]
I just saw that lite-flownet has a lot of weights, and I don’t know which one is better. Since you have tested it and the effect is almost the same, i don’t need to think about it. Thank you very much!
