### ISSUE TITLE
about shanghaitech dataset

### ISSUE THREAD

**Issue by sgq123** [feiyuhuahuo/Anomaly_Prediction#20]
hi,when i used shanghaitech dataset for training, there has been no response since the program started
but this code works well on avenue and ped2

**Comment by feiyuhuahuo** [comment]
https://github.com/feiyuhuahuo/Anomaly_Prediction/blob/6295f5d99553461df6689560b66303364059dfc8/Dataset.py#L117
please check here, maybe the path or the data format is not right.

**Comment by sgq123** [comment]
> https://github.com/feiyuhuahuo/Anomaly_Prediction/blob/6295f5d99553461df6689560b66303364059dfc8/Dataset.py#L117
> 
> 
> please check here, maybe the path or the data format is not right.
Thanks.
there is nothing wrong with the label_loader, but maybe your code about loading training dataset doesn't consider "shangghaitech", because I found training datasets :avenue and ped2 have different form with shangghaitech.
I don't know if I'm right

**Comment by feiyuhuahuo** [comment]
Maybe there's something wrong. I did not train shanghaitech since it's a large dataset. You can try to fix this problem.
