### ISSUE TITLE
How to output the abnormal frame?

### ISSUE THREAD

**Issue by sanersbug** [feiyuhuahuo/Anomaly_Prediction#22]
Thanks for your project, i have run the train and evaluate , but how to output the abnormal frame?

**Comment by feiyuhuahuo** [comment]
You need to set a threshold of `psnr`, then the target_frame whose related `psnr` is below this threshold can be output as an abnormal frame.
https://github.com/feiyuhuahuo/Anomaly_Prediction/blob/6295f5d99553461df6689560b66303364059dfc8/evaluate.py#L92

**Comment by sanersbug** [comment]
@feiyuhuahuo thank you for your reply, and how to set the threshold ？ if it have some principle?

**Comment by feiyuhuahuo** [comment]
You need to consult the psnr curve. If psnr has a high value for normal frames and low value for abnormal frames, then you can easily set a threshold to distinguish these two situations. But if don't, then maybe this model is not suitable for this occasion.

**Comment by sanersbug** [comment]
@feiyuhuahuo Thank you very much! your answer is very useful!!
