### ISSUE TITLE
Can you share at approximately what iteration does your model reach around 95% AUC for ped2? 

### ISSUE THREAD

**Issue by abhishekaich27** [feiyuhuahuo/Anomaly_Prediction#25]

**Comment by feiyuhuahuo** [comment]
I forgot.  You can try 30000 and keep an eye on AUC. It should converge quickly.

**Comment by abhishekaich27** [comment]
I converge quickly to 91% but then its very very slow. Is this normal?

**Comment by feiyuhuahuo** [comment]
Yes, that's also what happened to me. It converges very quickly at first, but the final several points take a relatively long time.
