### ISSUE TITLE
Question for "Dataset.py" file

### ISSUE THREAD

**Issue by abhishekaich27** [feiyuhuahuo/Anomaly_Prediction#26]
First of all, thank you for such a clean implementation and comments at different places to understand what's going on. Kudos and so much to learn. Also, cheers for still addressing issues! :)

So, in your `Dataset.py` file are you sampling multiple sequences or just in order the frames appear?
For example, if video frames are `[01, 02, 03, 04, 05, 06, 07, 08, 09, 10]` then are you doing (assuming input video length 5):

1. `[01, 02, 03, 04, 05]` and then`[06, 07, 08, 09, 10]`?
2. (or) Randomly sampling a sequence of 5 consecutive frames from the video (random start point).

If you doing the latter (point 2), are you sampling multiple times (in order to get more possible sequences from the same video)?

**Comment by feiyuhuahuo** [comment]
I'm using method 2, and yes, I sampling multiple times.
