### ISSUE TITLE
train.py 

### ISSUE THREAD

**Issue by qiangmao306** [feiyuhuahuo/Anomaly_Prediction#27]
我在训练时卡在dataloader循环之前。我注意到你在另一个工作 pre_ano_detection那边也有相同的问题，程序卡住下不去，你的这份代码我也遇到了同样的问题，请问你知道原因吗
![image](https://user-images.githubusercontent.com/68309080/135187546-c9bfbcb1-1acd-4c30-a504-307457c7b980.png)

**Comment by feiyuhuahuo** [comment]
查查模型能不能顺利读到数据

**Comment by youngupup** [comment]
@feiyuhuahuo ，请问您训练并测试过shanghai dataset吗？我用自己的数据集测试auc不是很理想。感谢您的工作

**Comment by feiyuhuahuo** [comment]
shanghaitech 太大了，没训练。这个模型的应用场景有限，只能用在规律运动场景，类似商场人流那种。

**Comment by youngupup** [comment]
> shanghaitech 太大了，没训练。这个模型的应用场景有限，只能用在规律运动场景，类似商场人流那种。

好的，感谢
