### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by Tiacy** [feiyuhuahuo/Anomaly_Prediction#3]
Hello,Thanks for your work!
I have a question,when I running the "train.py" in pycharm,it no problem.
However,when I used Linux terminal run "python train.py --datasets=avenue",it said "ModuleNotFoundError: No module named 'cupy' ".But my packages including the 'cupy'.Thus,I don't know where is the problem.
I'm looking forward for your response.Thanks!

**Comment by Tiacy** [comment]
when I running the train.py,the result like this:
![image](https://user-images.githubusercontent.com/50324863/78091669-2652bd00-7400-11ea-94db-fad051c6b6bd.png)
I don't know it's right or not.It took a long time without a next step.
When I running the "python train.py --dataset=avenue",the result like this :
![image](https://user-images.githubusercontent.com/50324863/78091892-c6104b00-7400-11ea-9634-2d79a40d99b7.png)

**Comment by feiyuhuahuo** [comment]
'No step after initializing' means the Dataloder didn't get datasets. Check your path of the dataset. 
The environment of your python in PyCharm and in terminal may be different. 
Run python in terminal and check the python environment. Mine is like this:
![image](https://user-images.githubusercontent.com/32631344/78098404-9a499100-7411-11ea-98f3-1ab67907b1ad.png)
And my python environment in PyCharm is like this:
![image](https://user-images.githubusercontent.com/32631344/78098563-03310900-7412-11ea-9e89-9a026bb6986a.png)
Make sure cupy is installed in the terminal python environment.

**Comment by Tiacy** [comment]
OK，Thank you!
Now I can run the "train.py" in pycharm by modifying the "dataloder".About terminal train,I try it later.
Thank you very much!
