### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by Tiacy** [feiyuhuahuo/Anomaly_Prediction#4]
Another question：For example，after I trained the Avenue/training datasets,how to do test the Avenue/testing datasets?

**Comment by feiyuhuahuo** [comment]
`python evaluate.py --dataset=ped2 --trained_model=ped2_26000.pth`, replace the related dataset name and model name

**Comment by Tiacy** [comment]
Thank you very much!
Now it can train in Linux terminal.As your said , the reason is the python environment different.
Actually,the "evaluate.py" just like a test file ,whereas the "test~~.py" out of work.
Right?

**Comment by feiyuhuahuo** [comment]
'evaluation', 'validation' and 'test' are the same sayings, I think. `test~~.py` is used to test some functions or scripts.
