### ISSUE TITLE
About running time.

### ISSUE THREAD

**Issue by LanduRi** [feiyuhuahuo/Anomaly_Prediction#5]
Hello, thank you so much for sharing such great code. I have a question. Your code is running at about 50 FPS, while the speed given in the original paper is 25 FPS. What do you think caused this? Is PyTorch faster? The original paper used TITAN, and I used 1080Ti.

**Comment by feiyuhuahuo** [comment]
PyTorch is not faster than Tensorflow. Their speeds are nearly equal I think. The difference depends on several factors. The calculating way, any other operations, ... I don't know clearly. But a high FPS makes sense because the generator: U-net is a small model and the image size is small.
