### ISSUE TITLE
About EER

### ISSUE THREAD

**Issue by Tiacy** [feiyuhuahuo/Anomaly_Prediction#6]
Hello，Could you tell me how to compute Equal Error Rate?
By the way,do you have any idea to improve your prediction model? 
Have you tried to add a reconstruction model after the prediction model?

**Comment by feiyuhuahuo** [comment]
I don't know Equal Error Rate.  You can set a threshold to distinguish the normal frame and the abnormal frame. To improve the model, a new and better GAN maybe is helpful.

**Comment by Tiacy** [comment]
OK.Thanks for your reply!

**Comment by Tiacy** [comment]
Another question , when training UCSD ped1/ped2 datasets,should we change "input_channels=12" into "input_channels=4", as the datasets are all grayscales and every image has one channel.

**Comment by feiyuhuahuo** [comment]
No need to change `input_channels`. Grey images will be treated  as 3 channels. OpenCV will deal with it automatically.

**Comment by Tiacy** [comment]
Get it！Thanks for your help!
