### ISSUE TITLE
About Unet

### ISSUE THREAD

**Issue by Tiacy** [feiyuhuahuo/Anomaly_Prediction#7]
Hello，
After I read your code，I found that the `unet.py` does not implement the `Concatenate `operation,as the picture shows. 
Am I right?
Thanks for your reply!
![image](https://user-images.githubusercontent.com/50324863/85525140-5f837d80-b63b-11ea-86e9-98969b61d393.png)

**Comment by feiyuhuahuo** [comment]
Implemented here.
https://github.com/feiyuhuahuo/Anomaly_Prediction/blob/779ced0e70dfed88a5cc5ec9b74d862de0d5f792/models/unet.py#L59
